language: node_js
node_js:
 - '6'

branches:
 - master
 
install:
 - npm install --save-dev gh-pages
 - npm install
 
before_install:
- openssl aes-256-cbc -K $encrypted_c72f5a3c6fd2_key -iv $encrypted_c72f5a3c6fd2_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.email "kutear@kutear.com"
- git config --global user.name "CI Auto"

cache:
  directories:
     - node-modules


script:
- npm run build

after_script:
- git clone git@github.com:Kutear/react-qiniu-client.git
- cd  react-qiniu-client
- git checkout gh-pages
- rm -rf *
- mv ../build/* .
- git add -A
- git commit -m "CI pages"
- git push origin gh-pages
